### ISSUE TITLE
[Suggestion] Teleport cooldown

### ISSUE THREAD

**Issue by SeruhioX** [masagameplay/MaSuiteTeleports#10]
Hello! I thought that since it was a replacement for other plugins I would have this feature, but it seems like not so I came here to suggest it.

I suggest that when a user sends a teleportation request to another and it is accepted, say something like "Teleport will start in x seconds, don't move" and a permission to ignore this cooldown.

My server and many others are based on an improvement of the experience of the players by his rank, so we have ranks that have more time on the server or more effort not to have this cooldown.

It would be a great addition, thanks for reading

**Comment by masagameplay** [comment]
Added in the latest rewrites.
