### ISSUE TITLE
Setting a spawn on a server which already has one results in other server's spawns being deleted.

### ISSUE THREAD

**Issue by TheClowner** [masagameplay/MaSuiteTeleports#17]
When using /setspawn on a server, if it already has a spawn of that type set, instead of just updating that one entry in the database, every spawn of that type changes to that server & location. Using /delspawn first|default before setting it does work around this.

For example, after setting a first and default spawn on some servers, the spawns table in the database looks like this:
https://imgur.com/4W8Ppqr

Then if I run /setspawn first again on my hub server:
https://imgur.com/6FQK1Dw

I'm using the latest dev builds of MaSuiteCore, Portals, Warps and Teleports on all of my servers and bungeecord.

**Comment by masagameplay** [comment]
Should be fixed in the rewrites.
