### ISSUE TITLE
Error bungee

### ISSUE THREAD

**Issue by jere62smi** [masagameplay/MaSuiteTeleports#27]
http://bin.mc-imperia.fr/xwaaHTmINF
http://bin.mc-imperia.fr/ttNXHlM2S0

**Comment by jere62smi** [comment]
For the moment I no longer have this message in my logs, I will close the ticket during the day if it is corrected.

**Comment by jere62smi** [comment]
The errors seem to occur when a server suddenly crashes or shuts down while the bungee is still launched, once the server crashes, the following errors appear

**Comment by masagameplay** [comment]
I've moved things from Hibernate into ORMLite so this fix should be now implemented in the latest rewrite builds.
