### ISSUE TITLE
Name cannot be abbreviated

### ISSUE THREAD

**Issue by s99889989** [masagameplay/MaSuiteTeleports#3]
For example, a person’s name is Pocaca
I need to enter /tpa pocaca , Can't just enter  /tpa po
Essentials plugins Can enter /tpa po

MaSuiteTeleports  'Create an issue' Link error.         Link to  MaSuiteChat  issue

**Comment by masagameplay** [comment]
Thank you for posting your suggestion/issue! I added this finder in https://github.com/masagameplay/MaSuiteTeleports/commit/518e438cb6e2040a87f74c9997cbf62719ee4f6b. This should be in Spigot's forums soon.
