### ISSUE TITLE
Error MaSuiteHomes

### ISSUE THREAD

**Issue by jere62smi** [masagameplay/MaSuiteTeleports#30]
http://bin.mc-imperia.fr/2SIPBFLpSt

**Comment by masagameplay** [comment]
This issue is related to BungeeChat (>.... [13:00:48 WARN]: Error dispatching event ServerSwitchEvent(player=Naymonz, from=BungeeServerInfo(name=rpg, socketAddress=/127.0.0.1:45565, restricted=false)) to listener dev.aura.bungeechat.event.BungeeChatEventsListener@4837595f)
