### ISSUE TITLE
Wrong teleport

### ISSUE THREAD

**Issue by T9C5F** [masagameplay/MaSuiteTeleports#9]
Let's assume we have 3 players: test, test2 and test3.
I am test2 and I want to teleport test to test3, but by typing "/tp test test3" I teleport myself to test3. I think it's important that test is a substring of test2

**Comment by masagameplay** [comment]
Hello, I have noticed that this issue and there will be fix for this in the future.

**Comment by masagameplay** [comment]
This should be fixed in https://github.com/masagameplay/MaSuiteTeleports/commit/ff83c44640dc4326791d6a2711ac72533be9dcba.
